

CREATE TABLE [dbo].[DM_ICBillNo](
	[PID] [int] IDENTITY(1,1) NOT NULL,
	[FBillID] [int] NOT NULL,
	[FPreLetter] [varchar](50) NOT NULL,
	[YearMonthDay] [varchar](6) NOT NULL,
	[FCurNo] [varchar](6) NOT NULL,
 CONSTRAINT [PK_DM_ICBillNo_PID] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


